# Generated by Django 5.2.14 on 2026-05-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerprofile",
            name="delivery_fee_base",
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="delivery_fee_per_km",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="free_delivery_over",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="loyalty_points",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
