# Generated by Django 5.2.14 on 2026-05-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_mealfavorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="is_special",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="meal",
            name="promo_price",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
