# Generated by Django 5.2.14 on 2026-05-29 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_meal_is_special_meal_promo_price"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MealImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="meals/gallery/")),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="meal",
            index=models.Index(
                fields=["seller", "-created_at"], name="catalog_mea_seller__2fa035_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meal",
            index=models.Index(
                fields=["category", "is_available"],
                name="catalog_mea_categor_73e823_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="meal",
            index=models.Index(
                fields=["is_special", "is_available"],
                name="catalog_mea_is_spec_57fcc7_idx",
            ),
        ),
        migrations.AddField(
            model_name="mealimage",
            name="meal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gallery",
                to="catalog.meal",
            ),
        ),
    ]
