# Generated by Django 5.2.14 on 2026-05-29 11:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="link",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="notification",
            name="related_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("order", "Commande"),
                    ("order_status", "Statut commande"),
                    ("follow", "Abonnement"),
                    ("review", "Avis"),
                    ("chat", "Message"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "is_read", "-created_at"],
                name="notificatio_recipie_684eac_idx",
            ),
        ),
    ]
