# Generated by Django 5.2.14 on 2026-06-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_phase3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('order', 'Commande'), ('order_status', 'Statut commande'), ('follow', 'Abonnement'), ('review', 'Avis'), ('chat', 'Message'), ('weather', 'Météo')], max_length=20),
        ),
    ]
