# Generated by Django 5.2.14 on 2026-05-29 00:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "À la livraison"),
                    ("wave", "Wave"),
                    ("orange_money", "Orange Money"),
                    ("free_money", "Free Money"),
                ],
                default="cash",
                max_length=20,
            ),
        ),
    ]
