# Generated by Django 5.2.14 on 2026-05-29 11:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["-updated_at"], name="chat_conver_updated_1f6ffe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "is_read", "created_at"],
                name="chat_messag_convers_6c68b2_idx",
            ),
        ),
    ]
