# Generated by Django 5.2.14 on 2026-06-05 22:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0005_order_stripe_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('platform', models.CharField(blank=True, max_length=40)),
                ('device_model', models.CharField(blank=True, max_length=120)),
                ('os_version', models.CharField(blank=True, max_length=40)),
                ('app_version', models.CharField(blank=True, max_length=40)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('last_latitude', models.FloatField(blank=True, null=True)),
                ('last_longitude', models.FloatField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=64)),
                ('event_count', models.PositiveIntegerField(default=0)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session client',
                'verbose_name_plural': 'Sessions clients',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='OrderContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('device_time', models.DateTimeField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=64)),
                ('brightness', models.FloatField(blank=True, null=True)),
                ('weather_condition', models.CharField(blank=True, max_length=40)),
                ('temperature_c', models.FloatField(blank=True, null=True)),
                ('weather_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_sunny', models.BooleanField(blank=True, null=True)),
                ('is_rainy', models.BooleanField(blank=True, null=True)),
                ('cloud_cover', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('platform', models.CharField(blank=True, max_length=40)),
                ('device_model', models.CharField(blank=True, max_length=120)),
                ('app_version', models.CharField(blank=True, max_length=40)),
                ('connection_type', models.CharField(blank=True, max_length=40)),
                ('battery_level', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='context', to='orders.order')),
            ],
            options={
                'verbose_name': 'Contexte commande',
                'verbose_name_plural': 'Contextes commande',
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('click', 'Clic'), ('screen_view', 'Vue écran'), ('tap', 'Tap'), ('order', 'Commande'), ('other', 'Autre')], default='other', max_length=20)),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('screen', models.CharField(blank=True, max_length=120)),
                ('element', models.CharField(blank=True, max_length=120)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('device_time', models.DateTimeField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=64)),
                ('brightness', models.FloatField(blank=True, help_text='Luminosité écran (0.0–1.0)', null=True)),
                ('weather_condition', models.CharField(blank=True, max_length=40)),
                ('temperature_c', models.FloatField(blank=True, null=True)),
                ('weather_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_sunny', models.BooleanField(blank=True, null=True)),
                ('cloud_cover', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('platform', models.CharField(blank=True, max_length=40)),
                ('device_model', models.CharField(blank=True, max_length=120)),
                ('app_version', models.CharField(blank=True, max_length=40)),
                ('connection_type', models.CharField(blank=True, max_length=40)),
                ('battery_level', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='orders.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='analytics.clientsession')),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='analytics_a_user_id_157d89_idx'), models.Index(fields=['name', '-created_at'], name='analytics_a_name_82eb48_idx'), models.Index(fields=['city'], name='analytics_a_city_b7e4d3_idx')],
            },
        ),
    ]
