# Generated by Django 5.2.14 on 2026-06-05 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Tableau Analytics',
                'verbose_name_plural': 'Tableau Analytics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContentEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('meal', 'Plat / Nourriture'), ('video', 'Vidéo'), ('short', 'Short')], db_index=True, max_length=20)),
                ('content_id', models.PositiveIntegerField(db_index=True)),
                ('content_title', models.CharField(blank=True, max_length=200)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('platform', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_engagements', to='analytics.clientsession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_engagements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Engagement contenu',
                'verbose_name_plural': 'Engagements contenu',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'content_id'], name='analytics_c_content_3faa6c_idx'), models.Index(fields=['user', '-created_at'], name='analytics_c_user_id_8c1a49_idx')],
            },
        ),
    ]
