# Generated by Django 5.2.14 on 2026-06-03 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='weathernudgelog',
            new_name='weather_wea_user_id_7e4356_idx',
            old_name='weather_wea_user_id_6e8f0a_idx',
        ),
    ]
